### ISSUE TITLE
Have tiles rendered in-engine

### ISSUE THREAD

**Issue by PistolRcks** [paulpage/py2048#11]
I see no reason why there needs to be images for each tile when they could be rendered in-engine such as with rounded rectangle code found [here](https://www.pygame.org/project-AAfilledRoundedRect-2349-.html). This would allow for variable colors and possibly increasing the limit from 2048 to some arbitrary number, not to mention allowing for better scalability.

**Comment by paulpage** [comment]
I agree. This is the approach I took in the JavaScript port of this game, and it works pretty well there for all the reasons you mentioned.

**Comment by paulpage** [comment]
Done.
