### ISSUE TITLE
Auto mode broken if not invoked immediately

### ISSUE THREAD

**Issue by paulpage** [paulpage/py2048#14]
Steps to reproduce:

1. Start a new game.
2. Make a move manually (with the arrow keys)
3. Enable auto mode (press 'a')

You will see tiles move off screen, and at the end you will get "game over" even if there is a blank space.

**Comment by biggles5107** [comment]
Seems to be fixed by #16

**Comment by paulpage** [comment]
> Seems to be fixed by #16

Agreed.
