### ISSUE TITLE
Drop macOS support?

### ISSUE THREAD

**Issue by biggles5107** [paulpage/py2048#24]
With the amount of OS-specific code that's starting to go into our game, I think it might be best to stop saying that we "theoretically" support macOS. None of us have any way of testing it.

@paulpage, what say you?

**Comment by biggles5107** [comment]
I thought the issue was that `pygame.freetype` was only available on Linux (see #23), but it turns out that's not the issue. I fixed that (#25) without adding any OS-specific code. So to be accurate, we still have no OS-specific code. But we probably should still discuss this.

**Comment by paulpage** [comment]
We can still mention that it might run on macOS, but I think we should remove the installation instructions that may or may not work, as well as the download links.

**Comment by biggles5107** [comment]
Works for me.
