### ISSUE TITLE
Tiles sometimes spawn on top of other tiles

### ISSUE THREAD

**Issue by biggles5107** [paulpage/py2048#9]
Right now I am almost positive there is code that checks for open spaces for tiles, but I have noticed that our current code for this doesn't work. What happens is sometimes tiles spawn on top of other tiles, and once you try to move the tiles, eventually you end up with a  `ValueError` and the game crashes. Here is what is outputted to the terminal at the time of crash:

```
Traceback (most recent call last):
  File "./2048.py", line 236, in <module>
    key_action[event.key]()
  File "./2048.py", line 198, in moveDown
    moveAll(0, 1, 'grid_y')
  File "./2048.py", line 158, in moveAll
    combineTile(tile, xmove, ymove)
  File "./2048.py", line 105, in combineTile
    tiles.remove(tile)
ValueError: list.remove(x): x not in list
```

**Comment by PistolRcks** [comment]
PR #13 should fix the issue.
